### ISSUE TITLE
can't able to open file selection window in mac ....

### ISSUE THREAD

**Issue by laxkarparas1** [timsneath/filepicker_windows#14]
======== Exception caught by gesture ===============================================================
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library (dlopen(ole32.dll, 1): image not found)

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      _ole32 (package:win32/src/ole32.dart:20:31)
#3      _ole32 (package:win32/src/ole32.dart)
#4      CoInitializeEx (package:win32/src/ole32.dart:178:27)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#c5d8f
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(689.9, 463.8)
  finalLocalPosition: Offset(86.0, 20.7)
  button: 1
  sent tap down

it gives this error....

**Comment by timsneath** [comment]
OK, the clue is in the title of this package... :) 

This is for Windows, not macOS.
