### ISSUE TITLE
Select Folder 

### ISSUE THREAD

**Issue by iampopal** [timsneath/filepicker_windows#15]
This package works great for selecting files, can we have select Folder or select directory functionality.

**Comment by whitemagehealing** [comment]
This seems to already be possible (although you can only select ONE folder) in the API, but it's just not documented super well yet.

``` dart
          final directory = DirectoryPicker().getDirectory();
          if (directory != null) {
            print(directory.path);
          }
```

**Comment by iampopal** [comment]
Thank you, file picker helped me too
