### ISSUE TITLE
The argument type Poiner<Pointer<NativeType>> can't be assigned to the parameter type Pointer<Pointer<COMObject>> 

### ISSUE THREAD

**Issue by kirill-21** [timsneath/filepicker_windows#17]
![image](https://user-images.githubusercontent.com/63228361/144012546-70bc242a-0267-46db-b865-e54fe91f5e4c.png)
After updating win32 package from ^2.2.10 to ^2.3.1 i can not build the project due to this issue in filepicker_windows package

**Comment by timsneath** [comment]
Ooh -- good catch. I'll fix; thank you for noting this.

**Comment by kevinxxq** [comment]
Hi All,
I got the errors too, Is there any method to solve it quickly like downgrade the dependency?
Now the whole project can't build and can't run any more.

Thank you.

**Comment by kirill-21** [comment]
> Hi All, I got the errors too, Is there any method to solve it quickly like downgrade the dependency? Now the whole project can't build and can't run any more.
> 
> Thank you.

Just use win32 2.2.10 version without an ^symbol
win32: 2.2.10

**Comment by kevinxxq** [comment]
> > Hi All, I got the errors too, Is there any method to solve it quickly like downgrade the dependency? Now the whole project can't build and can't run any more.
> > Thank you.
> 
> Just use win32 2.2.10 version without an ^symbol win32: 2.2.10

Thank you very much! It works now.

**Comment by timsneath** [comment]
Fixed in https://github.com/timsneath/filepicker_windows/commit/f5d33da8290ff8c1679e2c4ec830b1c5a72ecceb. Thanks for the report.
