### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by paulowender** [timsneath/filepicker_windows#9]
On run the FilePicker on linux i have this error:
 GLib-GObject-CRITICAL **: 17:53:12.212: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
Gtk-WARNING **: 17:53:12.255: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
flutter: Invalid argument(s): Failed to load dynamic library (ole32.dll: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)

**Comment by timsneath** [comment]
This is a Windows package. It only runs on Windows.

**Comment by paulowender** [comment]
Sorry, thank's

**Comment by VergeDX** [comment]
> This is a Windows package. It only runs on Windows.

Well but [pub.dev](https://pub.dev/packages/filepicker_windows) page shows this package support `FLUTTER` `ANDROID` `IOS` `LINUX` `MACOS` `WINDOWS`, maybe this is a mistake.

**Comment by timsneath** [comment]
Unfortunately today there are no means for a package that is not a plugin to express which platforms it supports. I thought we already had an open issue on this, but I couldn't find one, so I created the linked issue above.
